name: Deploy Blazor to Cloudflare Pages

on:
  push:
    branches:
      - master # Eğer ana dalınızın adı 'main' ise 'master' yerine 'main' yazın.

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # Linux tabanlı bir ortamda çalıştırılacak

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Depoyu klonlar

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4 # .NET SDK'yı kurar
        with:
          # BURAYI KENDİ BLazor PROJENİZİN .NET VERSİYONU İLE DEĞİŞTİRİN
          # Örn: '6.0.x', '7.0.x', '8.0.x'
          dotnet-version: '8.0.x' 

      - name: Change directory to Mylo.Web project # Mylo.Web projesinin olduğu klasöre git
        run: cd Mylo.Web

      - name: Restore dependencies
        run: dotnet restore # Bağımlılıkları geri yükle

      - name: Publish Blazor app
        run: dotnet publish -c Release -o output # Blazor uygulamasını derle ve yayınla
                                                # output klasörüne yayınlar
                                                # Bu adımda zaten Mylo.Web klasöründeyiz

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1 # Cloudflare Pages dağıtım aksiyonunu kullanır
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }} # GitHub Secrets'tan API token'ı alır
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} # GitHub Secrets'tan Account ID'yi alır
          projectName: mylo-web # Cloudflare Pages'taki projenizin adı
          directory: Mylo.Web/output/wwwroot # Yayınlanan dosyaların Cloudflare'a yükleneceği dizin
                                            # NOT: Bu yol, deponuzun kökünden itibaren olmalı
                                            # Yani Mylo.Web klasörünün içindeki output/wwwroot
          # branch: master # İsteğe bağlı: Hangi daldan dağıtım yapılacağını belirtir. Otomatik algılar.
